server_name: 'devLog-server'

log:
  path: '/Users/yeong/blog/devLog/bin/log'
  level: 'debug'
  name: 'server-log'

web:
  base_url: 'http://localhost:8080'
  app: 'index.template.html'
  public_path: '/Users/csohb/GolandProjects/devLog/front/blogFront/public'
  session_timeout:
  download_directory:
